<a href="https://colab.research.google.com/github/Happy-ryan/CLASS_PY_LIB_LEVELUP_Practice./blob/main/_Pandas_%ED%95%9C%EB%B2%88%EC%97%90_%EC%A0%9C%EB%8C%80%EB%A1%9C_%EB%B0%B0%EC%9A%B0%EA%B8%B0_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas 한번에 제대로 배우기




---



In [2]:
import numpy as np
import pandas as pd
pd.__version__

'1.3.5'

## Pandas 객체


### Series 객체

In [3]:
s = pd.Series([2,3,4,5,8])
s

0    2
1    3
2    4
3    5
4    8
dtype: int64

In [4]:
s.values

array([2, 3, 4, 5, 8])

In [5]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s[1]

3

In [7]:
s[1:3]

1    3
2    4
dtype: int64

In [8]:
s = pd.Series([2,3,4,5,8],index =['a','b','c','d','e'])
s

a    2
b    3
c    4
d    5
e    8
dtype: int64

In [9]:
s['c']

4

In [10]:
'b' in s

True

In [11]:
s = pd.Series([2,3,4,5,6], index=[1,3,5,7,9,])
s

1    2
3    3
5    4
7    5
9    6
dtype: int64

In [12]:
s[2:]

5    4
7    5
9    6
dtype: int64

In [13]:
s.unique()

array([2, 3, 4, 5, 6])

In [14]:
s.value_counts()

2    1
3    1
4    1
5    1
6    1
dtype: int64

In [15]:
s.isin([2,3])

1     True
3     True
5    False
7    False
9    False
dtype: bool

In [16]:
pop_tuple = {'서울특별시': 9720846,'부산광역시':3404423,'인천광역시':2947217,'대전광역시':1471040,'광주광역시':1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [17]:
population['서울특별시']

9720846

In [18]:
population['서울특별시':'인천광역시']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [21]:
pd.DataFrame([{"a":2,"b":4,"d":3},{"a":4,"b":5,"c":7}])

a  b    d    c
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [23]:
pd.DataFrame(np.random.rand(5,5),
             columns =['a','b','c','d','e'],
             index=[1,2,3,4,5])

a         b         c         d         e
1  0.764694  0.160240  0.626035  0.144298  0.505308
2  0.654601  0.350837  0.760598  0.189445  0.741343
3  0.243920  0.785935  0.521033  0.291440  0.784437
4  0.810610  0.236346  0.173611  0.713980  0.462013
5  0.125590  0.304790  0.688454  0.523706  0.697870

In [26]:
male_tuple = {'서울특별시': 4742275,'부산광역시':1668618,'인천광역시':1476813,'대전광역시':734441,'광주광역시':720060}
male = pd.Series(male_tuple)
male

서울특별시    4742275
부산광역시    1668618
인천광역시    1476813
대전광역시     734441
광주광역시     720060
dtype: int64

In [27]:
female_tuple = {'서울특별시': 4988571,'부산광역시':1735805,'인천광역시':1470404,'대전광역시':736599,'광주광역시':734988}
female = pd.Series(female_tuple)
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대전광역시     736599
광주광역시     734988
dtype: int64

In [29]:
korea_df = pd.DataFrame({'인구수':population,
                         '남자인구수':male,
                         '여자인구수':female})
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4742275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [31]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대전광역시', '광주광역시'], dtype='object')

In [32]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [34]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [35]:
korea_df['서울특별시':'대전광역시']

인구수    남자인구수    여자인구수
서울특별시  9720846  4742275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대전광역시  1471040   734441   736599

### Index 객체


In [37]:
idx = pd.Index([2,4,6,8,10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [38]:
idx[1]

4

In [39]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [40]:
idx[-1::]

Int64Index([10], dtype='int64')

In [41]:
idx[::2]

Int64Index([2, 6, 10], dtype='int64')

In [42]:
print(idx)
print(idx.size)
print(idx.shape)
print(idx.ndim)
print(idx.dtype)

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### Index 연산

In [51]:
idx1 = pd.Index([1,2,4,6,8])
idx2 = pd.Index([2,4,5,6,7])
print(idx1.append(idx2))
print(idx1.difference(idx2)) # 집합1의 차집합
print(idx1.intersection(idx2)) # 교집합
print(idx1 & idx2)
print(idx1.union(idx2)) # 합집합 - 중복불가
print(idx1.delete(0)) # 0은 인덱스를 의미한다
print(idx1.drop(1))
print(idx1 ^ idx2) # 여집합을 의미 - 교집합 제외 부분

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  # Remove the CWD from sys.path while we load stuff.




---



## 인덱싱(Indexing)

In [54]:
s = pd.Series([2,4,6,7,8],
              index=['a','b','c','d','e'])
print(s)

a    2
b    4
c    6
d    7
e    8
dtype: int64


In [55]:
s['b']

4

In [56]:
'b' in s

True

In [57]:
s.keys()

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [59]:
list(s.items())#items()튜플로 만드는 함수 #map(), items() 등 zip하게 묶이게 된다. 그러므로 list로 감싸야 한다.

[('a', 2), ('b', 4), ('c', 6), ('d', 7), ('e', 8)]

In [64]:
s['f'] = 10
s

a     2
b     4
c     6
d     7
e     8
f    10
dtype: int64

In [65]:
  s['a':'c']

a    2
b    4
c    6
dtype: int64

In [68]:
s[0:3]

a    2
b    4
c    6
dtype: int64

In [69]:
s[(s>2) & (s<9)] # 조건을 주고 특정한 값만 출력 가능

b    4
c    6
d    7
e    8
dtype: int64

### Series 인덱싱

In [70]:
s = pd.Series(['a','b','c','d','e'],
              index=[1,3,5,7,9])
print(s)

1    a
3    b
5    c
7    d
9    e
dtype: object


In [71]:
s[1]

'a'

In [72]:
s.iloc[1] # a(0),b(1),c(2),d(3),e(4) -iloc[인덱스,row]

'b'

In [73]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [74]:
s.reindex(range(10))

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [75]:
s.reindex(range(10), method = 'bfill') # NaN을 채워주는 것

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱


In [76]:
 korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4742275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [77]:
korea_df['남자인구수']

서울특별시    4742275
부산광역시    1668618
인천광역시    1476813
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [78]:
korea_df.남자인구수

서울특별시    4742275
부산광역시    1668618
인천광역시    1476813
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [79]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [82]:
korea_df['남녀비율'] = (korea_df['남자인구수']*100/korea_df['여자인구수'])
print(korea_df.남녀비율)

서울특별시     95.062795
부산광역시     96.129346
인천광역시    100.435867
대전광역시     99.707032
광주광역시     97.968946
Name: 남녀비율, dtype: float64


In [83]:
korea_df.values

array([[9.72084600e+06, 4.74227500e+06, 4.98857100e+06, 9.50627945e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [84]:
korea_df.T #기존의 행과 열 변경

서울특별시         부산광역시         인천광역시         대전광역시         광주광역시
인구수    9.720846e+06  3.404423e+06  2.947217e+06  1.471040e+06  1.455048e+06
남자인구수  4.742275e+06  1.668618e+06  1.476813e+06  7.344410e+05  7.200600e+05
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  7.365990e+05  7.349880e+05
남녀비율   9.506279e+01  9.612935e+01  1.004359e+02  9.970703e+01  9.796895e+01

In [85]:
korea_df.values[0]

array([9.72084600e+06, 4.74227500e+06, 4.98857100e+06, 9.50627945e+01])

In [86]:
korea_df.인구수

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

In [88]:
korea_df.loc[:'인천광역시',:'남자인구수'] #col명으로 슬라이싱 : 처음부터 인천광역시까지

인구수    남자인구수    여자인구수        남녀비율
서울특별시  9720846  4742275  4988571   95.062795
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [89]:
korea_df.loc[(korea_df.여자인구수>1000000)]

인구수    남자인구수    여자인구수        남녀비율
서울특별시  9720846  4742275  4988571   95.062795
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [90]:
korea_df.loc[(korea_df.인구수 < 2000000)]

인구수   남자인구수   여자인구수       남녀비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [91]:
korea_df.loc[(korea_df.인구수 >= 2500000)]

인구수    남자인구수    여자인구수        남녀비율
서울특별시  9720846  4742275  4988571   95.062795
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [92]:
korea_df.loc[korea_df.남녀비율 > 100]

인구수    남자인구수    여자인구수        남녀비율
인천광역시  2947217  1476813  1470404  100.435867

In [94]:
korea_df.loc[(korea_df.인구수 >2500000) & (korea_df.남녀비율 >100)]

인구수    남자인구수    여자인구수        남녀비율
인천광역시  2947217  1476813  1470404  100.435867

In [95]:
korea_df.iloc[:3,:2] #iloc은 정수인덱스를 사용하는 것

인구수    남자인구수
서울특별시  9720846  4742275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱싱(Multi Indexing)

* 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
* 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [97]:
idx_tuples = [("서울특별시",2010),('서울특별시',2020),
              ("부산특별시",2010),('부산특별시',2020),
              ("인천특별시",2010),('인천특별시',2020),
              ("대구특별시",2010),('대구특별시',2020),
              ("대전특별시",2010),('대전특별시',2020),
              ("광주특별시",2010),('광주특별시',2020)]
print(idx_tuples)

[('서울특별시', 2010), ('서울특별시', 2020), ('부산특별시', 2010), ('부산특별시', 2020), ('인천특별시', 2010), ('인천특별시', 2020), ('대구특별시', 2010), ('대구특별시', 2020), ('대전특별시', 2010), ('대전특별시', 2020), ('광주특별시', 2010), ('광주특별시', 2020)]


In [98]:
pop_tuples =[10312545,9720846,
             2567910, 3404423,
             2758296, 2947217,
             2511676, 2427954,
             1503664, 1471040,
             1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)
print(population)

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산특별시, 2010)     2567910
(부산특별시, 2020)     3404423
(인천특별시, 2010)     2758296
(인천특별시, 2020)     2947217
(대구특별시, 2010)     2511676
(대구특별시, 2020)     2427954
(대전특별시, 2010)     1503664
(대전특별시, 2020)     1471040
(광주특별시, 2010)     1454636
(광주특별시, 2020)     1455048
dtype: int64


In [99]:
midx = pd.MultiIndex.from_tuples(idx_tuples) #97line
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산특별시', 2010),
            ('부산특별시', 2020),
            ('인천특별시', 2010),
            ('인천특별시', 2020),
            ('대구특별시', 2010),
            ('대구특별시', 2020),
            ('대전특별시', 2010),
            ('대전특별시', 2020),
            ('광주특별시', 2010),
            ('광주특별시', 2020)],
           )

In [101]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산특별시  2010     2567910
       2020     3404423
인천특별시  2010     2758296
       2020     2947217
대구특별시  2010     2511676
       2020     2427954
대전특별시  2010     1503664
       2020     1471040
광주특별시  2010     1454636
       2020     1455048
dtype: int64

In [102]:
population[:,2010] #2010 전체 보여줘

서울특별시    10312545
부산특별시     2567910
인천특별시     2758296
대구특별시     2511676
대전특별시     1503664
광주특별시     1454636
dtype: int64

In [104]:
population['대전특별시',:] #대전광역시 보여줘

2010    1503664
2020    1471040
dtype: int64

In [105]:
korea_mdf = population.unstack() # 다중인덱스Series를 DataFrame으로 출력함
print(korea_mdf)

           2010     2020
광주특별시   1454636  1455048
대구특별시   2511676  2427954
대전특별시   1503664  1471040
부산특별시   2567910  3404423
서울특별시  10312545  9720846
인천특별시   2758296  2947217


In [106]:
korea_mdf.stack() # DataFrame 구조를 다중 인덱스 Series로 출력함

광주특별시  2010     1454636
       2020     1455048
대구특별시  2010     2511676
       2020     2427954
대전특별시  2010     1503664
       2020     1471040
부산특별시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천특별시  2010     2758296
       2020     2947217
dtype: int64

In [113]:
male_tuples = [5111259, 4732275,
              1773170, 1668618,
              1390356,1476813,
              1255245, 1198815,
              753648, 734441,
              721780, 720060]
male_tuples

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [114]:
korea_mdf =pd.DataFrame({'총인구수':population,'남자인구수':male_tuples})
korea_mdf

총인구수    남자인구수
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산특별시 2010   2567910  1773170
      2020   3404423  1668618
인천특별시 2010   2758296  1390356
      2020   2947217  1476813
대구특별시 2010   2511676  1255245
      2020   2427954  1198815
대전특별시 2010   1503664   753648
      2020   1471040   734441
광주특별시 2010   1454636   721780
      2020   1455048   720060

In [115]:
female_tuples =[5201286,4988571,
                1794740,1735805,
                1367940,1470404,
                1256431,1229139,
                750016,736599,
                732856,734988]

In [119]:
korea_mdf = pd.DataFrame({'총인구수':population,
                          '남자인구수':male_tuples,
                          '여자인구수':female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산특별시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천특별시 2010   2758296  1390356  1367940
      2020   2947217  1476813  1470404
대구특별시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전특별시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주특별시 2010   1454636   721780   732856
      2020   1455048   720060   734988

In [122]:
ratio = korea_mdf.남자인구수*100/korea_mdf.여자인구수
ratio

서울특별시  2010     98.269140
       2020     94.862336
부산특별시  2010     98.798155
       2020     96.129346
인천특별시  2010    101.638668
       2020    100.435867
대구특별시  2010     99.905606
       2020     97.532907
대전특별시  2010    100.484256
       2020     99.707032
광주특별시  2010     98.488653
       2020     97.968946
dtype: float64

In [123]:
ratio.unstack()

2010        2020
광주특별시   98.488653   97.968946
대구특별시   99.905606   97.532907
대전특별시  100.484256   99.707032
부산특별시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천특별시  101.638668  100.435867

In [125]:
korea_mdf = pd.DataFrame({'총인구수':population,
                          '남자인구수':male_tuples,
                          '여자인구수':female_tuples,
                         '남녀비율':ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산특별시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천특별시 2010   2758296  1390356  1367940  101.638668
      2020   2947217  1476813  1470404  100.435867
대구특별시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전특별시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주특별시 2010   1454636   721780   732856   98.488653
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [128]:
df = pd.DataFrame(np.random.rand(6,3),# 6행 3열의 난수 생성
                  index = [['a','b','c','a','c','b'],[1,2,1,2,1,2]],
                  columns =['c1','c2','c3'])
df

c1        c2        c3
a 1  0.119294  0.891666  0.815181
b 2  0.232813  0.737709  0.023967
c 1  0.394748  0.929522  0.516124
a 2  0.666639  0.532410  0.656294
c 1  0.075702  0.959718  0.549247
b 2  0.531525  0.907667  0.660988

In [129]:
pd.MultiIndex.from_arrays( [['a','b','c','a','c','b'],[1,2,1,2,1,2]])


MultiIndex([('a', 1),
            ('b', 2),
            ('c', 1),
            ('a', 2),
            ('c', 1),
            ('b', 2)],
           )

In [130]:
pd.MultiIndex.from_tuples([('a',1),('b',2),('c',1),('a',2),('c',1),('b',2)])

MultiIndex([('a', 1),
            ('b', 2),
            ('c', 1),
            ('a', 2),
            ('c', 1),
            ('b', 2)],
           )

In [131]:
pd.MultiIndex.from_product([['a','b','c'],[1,2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [ ]:
pd.MultiIndex(levels = )

#### 인덱싱 및 슬라이싱

#### 다중 인덱스 재정렬

## 데이터 연산

### 연산자 범용 함수


#### add()

#### sub() / subtract()

#### mul() / multply()




#### truediv() /  div() / divide() / floordiv()

#### mod()

#### pow()

### 정렬(Sort)

### 순위(Ranking)


### 고성능 연산

## 데이터 결합

### Concat() / Append()

### 병합과 조인

## 데이터 집계와 그룹 연산

#### 집계 연산(Aggregation)


### GroupBy 연산

### 피벗 테이블(Pivot Table)


### 범주형(Categorical) 데이터


## 문자열 연산

#### 문자열 연산자

#### 기타 연산자


#### 정규표현식


## 시계열 처리

#### 시계열 데이터 구조


### 시계열 기본

### 주기와 오프셋


### 시프트(Shift)

### 시간대 처리

* 국제표준시(Coordinated Universal Time, UTC)를 기준으로 떨어진 거리만큼 오프셋으로 시간대 처리
* 전 세계의 시간대 정보를 모아놓은 올슨 데이터베이스를 활용한 라이브러리인 `pytz` 사용

### 기간과 기간 연산

### 리샘플링(Resampling)

* 리샘플링(Resampling): 시계열의 빈도 변환
* 다운샘플링(Down sampling): 상위 빈도 데이터를 하위 빈도 데이터로 집계
* 업샘플링(Up sampling): 하위 빈도 데이터를 상위 빈도 데이터로 집계

### 무빙 윈도우(Moving Window)

## 데이터 읽기 및 저장


### 텍스트 파일 읽기/쓰기

### 이진 데이터 파일 읽기/쓰기

## 데이터 정제

### 누락값 처리

* 대부분의 실제 데이터들은 정제되지 않고 누락값들이 존재
* 서로 다른 데이터들은 다른 형태의 결측을 가짐
* 결측 데이터는 `null`, `NaN`, `NA`로 표기

#### None: 파이썬 누락 데이터

#### NaN: 누락된 수치 데이터

#### Null 값 처리


### 중복 제거

### 값 치환

## 참고문헌

* Pandas 사이트: https://pandas.pydata.org/
* Jake VanderPlas, "Python Data Science Handbook", O'Reilly
* Wes Mckinney, "Python for Data Analysis", O'Reilly